<section class="register">

<h2>Login</h2>

<?php if ($this->errors): ?>
  <p class="error">
    There were one of more issues with your submission. Please correct them as indicated below.
  </p>
<?php endif; ?>

<?php 

$form = $this->form;

$form->prepare();

$form->setAttribute('action', $this->url(NULL, array(
  'controller' => 'Users',
  'action' => 'login',
)));

echo $this->form()->openTag($form);

?>

<dl class="zend_form">
  
  <dt><?php echo $this->formLabel($form->get('email')); ?></dt>
  <dd><?php
  
  echo $this->formElement($form->get('email'));
  echo $this->formElementErrors($form->get('email'));
  
  ?></dd>
  
  <dt><?php echo $this->formLabel($form->get('password')); ?></dt>
  <dd><?php
  
  echo $this->formElement($form->get('password'));
  echo $this->formElementErrors($form->get('password'));
  
  ?></dd>
  
  <dd><?php
  
  echo $this->formElement($form->get('submit'));
  echo $this->formElementErrors($form->get('submit'));
  
  ?></dd>
</dl>

<?php echo $this->form()->closeTag(); ?>
